### PR TITLE
Feature: Remove Glint on Armor When Damaged option and individual Affect Armor options

### LINKED ISSUE #4: hitcolor mod isnt consistent
When beeing hit the color is different if you wear enchanted armor from normal armor, you can see the difference below. Lunar has the color consistent and badlion used to have this bug too but i reported it and they fixed it.

### PR DESCRIPTION
**Pull request by Tellinq**
Resolves #4

### CODE REVIEW

**Comment by GoXLR** [comment]
Nox's work that he was entitled to do.

**Comment by Noxiuam** [comment]
> Nox's work that he was entitled to do.

i have other things to do other than code minecraft mods 🤓

**Comment by dotslashlevi** [comment]
> Nox's work that he was entitled to do.

She* you transphobic mccdonald doncic slow toad bih totalitarian hoe kid yo uncle lookin like a copy of George Orwell's book "1984" because of the fact that he makes propeganda for your anus gay ass mf yo dad looks like a femboy in a skirt goofy ahh kid lmao

**Comment by dotslashlevi** [comment]
Don't think im done with you yet boy i had to get off the bus Dw yo grandma tastes like a fish with prostate cancer dick flapper crip thrower dick blower chip eater blick sheeter brick pee-er kid creeper (kan)ye supporter antifa gorer shit whorer shtick oraler factory tourer lookin ahhhhh. Yo ass looks like a gay man with a straight man onii chan pedo fam Yeat jam twizzy RAM dick cram kick land ocean sand toe bland hoe glammed tor hacker-manned lookin assssss. Get outta here you goofy ahh kid 🫵😹

**Pull request merged**
